---
# This role contains common plays that will run on all nodes.

- name: Install python bindings for SE Linux
  yum:
   name:
    - libselinux-python
    - libsemanage-python

- name: Install epel-release
  yum:
   name: epel-release
   state: present

- name: Allow local network
  ansible.posix.firewalld:
    zone: trusted
    source: '{{ network }}'
    permanent: yes
    state: enabled
  notify: reload firewalld

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
