---
# This role installs Nginx and configures it.

- name: Download and install nginx
  yum: 
   name: nginx
   state: present

- name: Configure the nginx conf file with hosts
  template: 
   src: nginx.conf.j2
   dest: /etc/nginx/nginx.conf
  notify: reload nginx

- name: Start the nginx service
  ansible.builtin.service:
   name: nginx
   state: started
   enabled: yes

- name: permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled
  notify: reload firewalld
