---
## This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: all

  roles:
  - common
  - monitoring-node

# Configure and deploy database servers.
- hosts: dbservers

  roles:
  - base-db
  - master-db

  tags:
  - db

# Configure and deploy slave database servers.
- hosts: dbslaves

  roles:
  - base-db
  - slave-db

  vars_files:
  - group_vars/dbservers

  tags:
  - db

# Configure and deploy the web servers. Note that we include two roles here,
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: webservers

  roles:
  - base-apache
  - web

  vars_files:
  - group_vars/dbservers

  tags:
  - web

# Configure and deploy the load balancer(s).
- hosts: lbservers

  roles:
  - nginx

  tags:
  - lb

# Configure and deploy the Prometheus monitoring node(s).
- hosts: monitoring

  roles:
  - monitoring

  tags:
  - monitoring
